#!/usr/bin/python

import sys, socket
from subprocess import Popen, PIPE

SERVER_HOST = '0.0.0.0'
SERVER_PORT = 8401


def main():
  run = False
  if len(sys.argv) > 0:
    if sys.argv[1] == "-d":
      run = True
  if not run:
    print("Usage: systemctl start kioskms.service")
    exit(1)

  server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
  server_socket.bind((SERVER_HOST, SERVER_PORT))
  server_socket.listen(1)
  print('Listening on port %s ...' % SERVER_PORT)

  while True:
    client_connection, client_address = server_socket.accept()
    request = client_connection.recv(1024).decode()
    if client_address[0] != '127.0.0.1':
      print("Connection not allowed: {}".format(client_address[0]))
    else:
      cmd = ""
      print(request.split(' ')[1][1:].lower())
      if request.split(' ')[1][1:].lower() == "next":
        cmd = "export DISPLAY=:0; xdotool key ctrl+r; xdotool key ctrl+Tab"
      if len(cmd) > 0:
        prc = Popen(["bash", "-c", "{}".format(cmd)], stdin=PIPE, stdout=PIPE, stderr=PIPE)
    response = 'HTTP/1.0 200 OK\n'
    client_connection.sendall(response.encode())
    client_connection.close()

  server_socket.close()

if __name__ == "__main__":
    main()